FROM golang:1.7.3-alpine

ENV GOPATH /go

RUN mkdir -p "$GOPATH/src/" "$GOPATH/bin" && chmod -R 777 "$GOPATH" && \
    mkdir -p /go/src/github.com/yunify/docker-plugin-hostnic

RUN apk --update add bash git && \
    ln -s /go/src/github.com/yunify/docker-plugin-hostnic /app

WORKDIR /app
